[tools]
typst = "0.14.0"

[env]
TYPST_FONT_PATHS = "{{config_root}}/assets/fonts"
TYPST_ROOT = "{{config_root}}"

[tasks.compile-all]
run = """
#!/usr/bin/env bash

find . -type f -name "*.typ" ! -name "*.tpl.typ" -print0 |
xargs -0 -n1 -P4 typst compile
"""
